Repository Babylonpartners/Bento, pull requests merged in 2018-11, with the labels that each got.

#59 Include `Screen` components which were not included
  BentoKit/BentoKit.xcodeproj/project.pbxproj
  BentoKit/BentoKit/Components/DatePicker.swift
  BentoKit/BentoKit/Helpers/Extensions/Bool+Assertions.swift
  BentoKit/BentoKit/Helpers/Extensions/BoxExtensions.swift
  BentoKit/BentoKit/Helpers/Extensions/UIButton+Closure.swift
  BentoKit/BentoKit/Helpers/Extensions/UIViewAnimationOptions+Curve.swift
  BentoKit/BentoKit/Helpers/With.swift
  BentoKit/BentoKit/Screen/BoxAppearance.swift
  BentoKit/BentoKit/Screen/BoxRenderer.swift
  BentoKit/BentoKit/Screen/BoxViewController.swift
  BentoKit/BentoKit/Screen/BoxViewModel.swift
  BentoKit/BentoKit/Screen/Screen.swift
  BentoKit/BentoKit/Views/BentoTableView.swift
  BentoKit/BentoKitTests/SnapshotTests/Screen/BoxViewControllerSnapshotTests.swift
  BentoKit/BentoKitTests/SnapshotTests/Utilities/FBSnapshotTestCaseExtensions.swift
  BentoKit/BentoKitTests/SnapshotTests/Utilities/HostWindow.swift
  Snapshots/ReferenceImages_64/BentoKitTests.BoxViewControllerSnapshotTests/testWithYCenterAligned_iPhone6@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.BoxViewControllerSnapshotTests/testWithYCenterAligned_iPhone6Plus@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.BoxViewControllerSnapshotTests/testWithYCenterAligned_iPhoneX@2x.png
Labels: ready for review

#63 Support for `NavigationTitleItem` in `Screen`. Resolves #61
  BentoKit/BentoKit/Screen/BoxViewController.swift
  BentoKit/BentoKit/Screen/Screen.swift
  BentoKit/BentoKitTests/SnapshotTests/Screen/BoxViewControllerSnapshotTests.swift
  Snapshots/ReferenceImages_64/BentoKitTests.BoxViewControllerSnapshotTests/testWithYCenterAligned_StringTitle_iPhone6@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.BoxViewControllerSnapshotTests/testWithYCenterAligned_StringTitle_iPhone6Plus@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.BoxViewControllerSnapshotTests/testWithYCenterAligned_StringTitle_iPhoneX@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.BoxViewControllerSnapshotTests/testWithYCenterAligned_ViewTitle_iPhone6@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.BoxViewControllerSnapshotTests/testWithYCenterAligned_ViewTitle_iPhone6Plus@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.BoxViewControllerSnapshotTests/testWithYCenterAligned_ViewTitle_iPhoneX@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.BoxViewControllerSnapshotTests/testWithYCenterAligned_iPhone6@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.BoxViewControllerSnapshotTests/testWithYCenterAligned_iPhone6Plus@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.BoxViewControllerSnapshotTests/testWithYCenterAligned_iPhoneX@2x.png
Labels: enhancement, ready for review

#64 Fix the podspec for BentoKit.
  BentoKit.podspec
Labels: bug, ready for review

#62 Custom Adapter & Component Lifecycle Messages for UICollectionView.
  Bento.xcodeproj/project.pbxproj
  Bento/Adapters/CollectionViewAdapter.swift
  Bento/Adapters/CollectionViewDataSource.swift
  Bento/Adapters/TableViewAdapter.swift
  Bento/Bento/UICollectionViewExtensions.swift
  Bento/Diff/CollectionViewSectionDiff.swift
  Bento/Diff/TableViewSectionDiff.swift
  Bento/Helpers.swift
  Bento/Views/BentoReusableView.swift
  Bento/Views/Box.swift
  Bento/Views/CollectionViewContainerCell.swift
  Bento/Views/CollectionViewContainerReusableView.swift
  Bento/Views/TableViewContainerCell.swift
  Bento/Views/TableViewHeaderFooterView.swift
  Example/CollectionViewExample/CustomCollectionViewAdapter.swift
  Example/CollectionViewExample/IntroComponent.swift
  Example/CollectionViewExample/IntroViewController.swift
  README.md
Labels: ready for review

#66 Use multiline UILabel for the UIPickerView component view
  BentoKit/BentoKit/Helpers/ListPickerAdapter.swift
  BentoKit/BentoKitTests/SnapshotTests/Components/OptionPickerSnapshotTests.swift
  Snapshots/ReferenceImages_64/BentoKitTests.OptionPickerSnapshotTests/test_default_iPhone6@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.OptionPickerSnapshotTests/test_default_iPhone6Plus@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.OptionPickerSnapshotTests/test_default_iPhoneX@2x.png
Labels: bug, ready for review

#60 Add support for `UIMenuController` actions when user long press item in [UI]TableView/CollectionView
  Bento.xcodeproj/project.pbxproj
  Bento/Adapters/CollectionViewAdapter.swift
  Bento/Adapters/TableViewAdapter.swift
  Bento/Renderable/MenuItemsResponding.swift
  Bento/Views/CollectionViewContainerCell.swift
  Bento/Views/CollectionViewContainerReusableView.swift
  Bento/Views/TableViewContainerCell.swift
  Bento/Views/TableViewHeaderFooterView.swift
Labels: feature request, ready for review

#68 Include the asset catalog in the pod resource bundle
  BentoKit.podspec
  BentoKit/BentoKit.xcodeproj/project.pbxproj
  BentoKit/BentoKit/Views/Accessory.swift
  BentoKit/BentoKit/Views/FocusToolbar.swift
  BentoKit/BentoKit/Views/Resources.swift
Labels: bug, ready for review

#70 Fix issue with bar button item not resigning first responder
  BentoKit/BentoKit/Screen/BoxViewController.swift
  BentoKit/BentoKit/Screen/Screen.swift
Labels: bug

#71 Put `isEnabled` back as it was accidentally removed in the last PR
  BentoKit/BentoKit/Screen/Screen.swift
Labels: bug

#69 Added search bar component
  BentoKit/BentoKit.xcodeproj/project.pbxproj
  BentoKit/BentoKit/Components.playground/Pages/Search.xcplaygroundpage/Contents.swift
  BentoKit/BentoKit/Components.playground/Pages/Search.xcplaygroundpage/timeline.xctimeline
  BentoKit/BentoKit/Components.playground/contents.xcplayground
  BentoKit/BentoKit/Components/Search.swift
  BentoKit/BentoKitTests/SnapshotTests/Components/SearchSnapshotTests.swift
  Snapshots/ReferenceImages_64/BentoKitTests.SearchSnapshotTests/testSearch_iPhone6@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.SearchSnapshotTests/testSearch_iPhone6Plus@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.SearchSnapshotTests/testSearch_iPhoneX@2x.png
  StyleSheets/StyleSheets.xcodeproj/project.pbxproj
  StyleSheets/StyleSheets/SearchBarStyleSheet.swift
Labels: enhancement, ready for review

#74 Handle nil IndexPath for `canPerformAction`
  Bento/Adapters/CollectionViewAdapter.swift
Labels: bug

#75 Allow providing custom views as accessory
  BentoKit/BentoKit/Components.playground/Pages/TitledDescription.xcplaygroundpage/Contents.swift
  BentoKit/BentoKit/Components.playground/Pages/TitledDescription.xcplaygroundpage/timeline.xctimeline
  BentoKit/BentoKit/Components/TitledDescription.swift
  BentoKit/BentoKit/Views/Accessory.swift
  BentoKit/BentoKitTests/SnapshotTests/Components/TitledDescriptionSnapshotTests.swift
  Snapshots/ReferenceImages_64/BentoKitTests.TitledDescriptionSnapshotTests/test_considers_custom_accessory_view_size_iPhone6@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.TitledDescriptionSnapshotTests/test_considers_custom_accessory_view_size_iPhone6Plus@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.TitledDescriptionSnapshotTests/test_considers_custom_accessory_view_size_iPhoneX@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.TitledDescriptionSnapshotTests/test_with_custom_accessory_view_iPhone6@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.TitledDescriptionSnapshotTests/test_with_custom_accessory_view_iPhone6Plus@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.TitledDescriptionSnapshotTests/test_with_custom_accessory_view_iPhoneX@2x.png
Labels: enhancement

#73 Show search bar cancel button with animation
  BentoKit/BentoKit/Components/Search.swift
  BentoKit/BentoKitTests/SnapshotTests/Components/SearchSnapshotTests.swift
  StyleSheets/StyleSheets/SearchBarStyleSheet.swift
Labels: enhancement

#77 Added accessory view stylesheet to TitledDescription
  BentoKit/BentoKit/Components/TitledDescription.swift
Labels: enhancement, ready for review

#78 Fix possible autolayout loop when using an ImageOrLabel/TitledDescription component in a section header
  BentoKit/BentoKit/Views/ImageOrLabelView.swift
Labels: bug, ready for review

#79 Add line break mode for Button and Label stylesheets
  StyleSheets/StyleSheets/ButtonStyleSheet.swift
  StyleSheets/StyleSheets/LabelStyleSheet.swift
  StyleSheets/StyleSheetsTests/StyleSheetTests.swift
Labels: enhancement, ready for review

#76 Refactor TitledDescription styling
  BentoKit/BentoKit/Components/TitledDescription.swift
  BentoKit/BentoKit/Views/BaseView.swift
Labels: enhancement, ready for review
