Repository Babylonpartners/Bento, pull requests merged in 2018-05, with the labels that each got.

#27 Couple of formatting/grammar fixes
  README.md
Labels: enhancement

#29 Added documentation for conditional operators
  README.md
Labels: ready for review

#30 Avoid name collisions while computing `reuseIdentifier`
  Bento.xcodeproj/project.pbxproj
  Bento/Renderable/Renderable.swift
  BentoTests/RenderableTests.swift
Labels: bug, ready for review

#32 Replace `_typeName(_:qualified:)` by `String(reflecting:)` which is safe for metatypes
  Bento/Renderable/Renderable.swift
Labels: ready for review
