Repository Babylonpartners/Bento, pull requests merged in 2018-10, with the labels that each got.

#52 Treat sections move as `insertion` + `deletion`
  Bento/Diff/TableViewSectionDiff.swift
Labels: bug, ready for review

#53 Use destination section for destination indexPath
  Bento/Diff/TableViewSectionDiff.swift
Labels: bug, ready for review

#54 OSS StyleSheets 💅
  .circleci/config.yml
  Bento.xcodeproj/project.pbxproj
  Bento.xcworkspace/contents.xcworkspacedata
  StyleSheets.podspec
  StyleSheets/StyleSheets.xcodeproj/project.pbxproj
  StyleSheets/StyleSheets.xcodeproj/xcshareddata/xcschemes/StyleSheets.xcscheme
  StyleSheets/StyleSheets/ActivityIndicatorStyleSheet.swift
  StyleSheets/StyleSheets/ButtonStyleSheet.swift
  StyleSheets/StyleSheets/ImageViewStyleSheet.swift
  StyleSheets/StyleSheets/Info.plist
  StyleSheets/StyleSheets/LabelStyleSheet.swift
  StyleSheets/StyleSheets/StackViewStyleSheet.swift
  StyleSheets/StyleSheets/StyleSheet.swift
  StyleSheets/StyleSheets/TableViewStyleSheet.swift
  StyleSheets/StyleSheets/TextAlignment.swift
  StyleSheets/StyleSheets/TextBoundComputing.swift
  StyleSheets/StyleSheets/TextViewStyleSheet.swift
  StyleSheets/StyleSheets/ViewStyleSheet.swift
  StyleSheets/StyleSheetsTests/Info.plist
  StyleSheets/StyleSheetsTests/StyleSheetTests.swift
Labels: enhancement, ready for review

#55 Include build configuration files to share configurations across modules
  Bento.xcodeproj/project.pbxproj
  BuildConfigs/Framework.Base.xcconfig
  BuildConfigs/Framework.Debug.xcconfig
  BuildConfigs/Framework.Release.xcconfig
  StyleSheets/StyleSheets.xcodeproj/project.pbxproj
Labels: ready for review
