Repository Babylonpartners/Bento, pull requests merged in 2018-08, with the labels that each got.

#31 Allow custom table view adapter type.
  Bento.xcodeproj/project.pbxproj
  Bento/Adapters/TableViewAdapter.swift
  Bento/Bento/Box.swift
  Bento/Bento/Node.swift
  Bento/Bento/Section.swift
  Bento/Bento/UITableViewExtensions.swift
  Bento/Helpers.swift
  Bento/Renderable/AnyRenderable.swift
  Example/BookAppointmentViewController.swift
Labels: enhancement, ready for review

#40 Extend the sizing API to support inherited layout margins.
  Bento/Bento/Node.swift
  Bento/Bento/Section.swift
  Bento/Renderable/AnyRenderable.swift
Labels: enhancement, ready for review

#38 Focus Control.
  Bento.xcodeproj/project.pbxproj
  Bento/Adapters/BentoCollectionView.swift
  Bento/Adapters/CollectionViewDataSource.swift
  Bento/Adapters/FocusEligibilitySource.swift
  Bento/Adapters/TableViewAdapter.swift
  Bento/Adapters/UIKit+BentoCollectionView.swift
  Bento/Bento/Box.swift
  Bento/Bento/Node.swift
  Bento/Bento/UITableViewExtensions.swift
  Bento/Helpers.swift
  Bento/Renderable/AnyRenderable.swift
  Bento/Renderable/Deletable.swift
  Bento/Renderable/FocusCoordinator.swift
  Bento/Renderable/Focusable.swift
  Bento/Renderable/FocusableView.swift
  Bento/Renderable/UIKit+CollectionViewFocus.swift
  Example/Base.lproj/Main.storyboard
  Example/Cells/MovieComponentView.swift
  Example/Cells/TextFieldComponent.swift
  Example/PersonalDetailsViewController.swift
Labels: enhancement

#43 Set clear color to the content view
  Bento/Views/CollectionViewContainerCell.swift
  Bento/Views/TableViewContainerCell.swift
  Bento/Views/TableViewHeaderFooterView.swift
Labels: enhancement

#45 Use contentView when appropriate. Fixed supplementary view updates.
  Bento.xcodeproj/project.pbxproj
  Bento/Adapters/CollectionViewDataSource.swift
  Bento/Adapters/UIKit+BentoCollectionView.swift
  Bento/Diff/Changeset+MutationIndexPairs.swift
  Bento/Diff/CollectionViewSectionDiff.swift
  Bento/Diff/TableViewSectionDiff.swift
  Bento/Views/BentoReusableView.swift
  Bento/Views/Box.swift
  Bento/Views/CollectionViewContainerReusableView.swift
  Example/CollectionViewExample/IntroRenderer.swift
  Example/CollectionViewExample/IntroViewController.swift
  Example/ViewController.swift
Labels: ready for review
