Repository Babylonpartners/Bento, pull requests merged in 2019-04, with the labels that each got.

#138 Expose contentView spacing via Toggle builder
  BentoKit/BentoKit/Components/Toggle.swift
Labels: enhancement, ready for review

#140 Allow setting titleEdgeInsets on buttons
  StyleSheets/StyleSheets/ButtonStyleSheet.swift
Labels: enhancement

#123 Improves documentation of Bento
  Bento/Bento/Node.swift
  Bento/Bento/Section.swift
  Bento/Renderable/Renderable.swift
  Bento/Views/Box.swift
  BentoKit/BentoKit/Components/Component.swift
  BentoKit/BentoKit/Components/DatePicker.swift
  BentoKit/BentoKit/Components/MultilineTextInput.swift
  BentoKit/BentoKit/Components/OptionPicker.swift
  BentoKit/BentoKit/Components/Search.swift
  BentoKit/BentoKit/Components/TextInput.swift
  BentoKit/BentoKit/Components/TitledDescription.swift
  BentoKit/BentoKit/Components/Toggle.swift
  BentoKit/BentoKit/Helpers/BoxTableViewAdapter.swift
  Documentation/common_usecases.md
  Example/AppDelegate.swift
  README.md
  Resources/example1.gif
  Resources/example2.gif
  Resources/example3.gif
  StyleSheets/StyleSheets/StyleSheet.swift
  StyleSheets/StyleSheets/ViewStyleSheet.swift
Labels: ready for review

#141 Introduce `AdapterStore` and integrate it with the TableView adapters.
  Bento.xcodeproj/project.pbxproj
  Bento/Adapters/AdapterProtocol.swift
  Bento/Adapters/AdapterStore.swift
  Bento/Adapters/TableViewAdapter.swift
  Bento/Bento/UITableViewExtensions.swift
  Bento/CollectionViews+Public/SizeCachingTableView.swift
  Bento/Diff/TableViewSectionDiff.swift
  BentoKit/BentoKit/Helpers/BoxTableViewAdapter.swift
  BentoTests/AdapterStoreTests.swift
Labels: ready for review

#147 AdapterStore should report non-existing supplement before disablement of caching.
  Bento/Adapters/AdapterStore.swift
  BentoTests/AdapterStoreTests.swift
Labels: bug, ready for review

#145 Upgrade BoxViewController to use the size caching BoxViewController.
  Bento.xcodeproj/project.pbxproj
  BentoKit/BentoKit.xcodeproj/project.pbxproj
  BentoKit/BentoKit/Components/EmptySpace.swift
  BentoKit/BentoKit/Screen/BoxViewController.swift
  BentoKit/BentoKit/Views/BoxSizeCachingTableView.swift
Labels: ready for review

#151 Stop using `performWithoutAnimation` to suppress animations for initial binding.
  BentoKit/BentoKit/Screen/BoxViewController.swift
Labels: ready for review

#150 Fix an adapter instantiation issue in BoxViewController.
  Bento.xcodeproj/project.pbxproj
  Bento/Adapters/CollectionViewAdapter.swift
  Bento/Adapters/TableViewAdapter.swift
  BentoTests/SizeCachingTableViewTests.swift
Labels: bug, ready for review

#153 Lower the empty space height constraint priority.
  BentoKit/BentoKit/Components/EmptySpace.swift
Labels: bug, ready for review

#152 Add separator height when using cached row size.
  Bento/Adapters/TableViewAdapter.swift
  BentoKit/BentoKitTests/SnapshotTests/Screen/BoxViewControllerSnapshotTests.swift
  Snapshots/ReferenceImages_64/BentoKitTests.BoxViewControllerSnapshotTests/test_separatorsEnabled_iPhone6@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.BoxViewControllerSnapshotTests/test_separatorsEnabled_iPhone6Plus@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.BoxViewControllerSnapshotTests/test_separatorsEnabled_iPhoneX@2x.png
Labels: bug, ready for review

#149 Propagate `ViewLifecycleAware` calls to the entire view hierarchy.
  Bento/Views/BentoReusableView.swift
Labels: ready for review

#156 Bumped dependencies for Swift 4.2
  BentoKit.podspec
Labels: ready for review

#154 Remove workarounds that are superseded by `PreSizingLayoutPassRequiring`.
  BentoKit/BentoKit/Screen/BoxViewController.swift
Labels: bug

#158 Custom Input with Highlighting Gesture behavior.
  Bento.xcodeproj/project.pbxproj
  Bento/Components/DetailedDescription.swift
  Bento/Renderable/CustomInputComponent.swift
  Bento/Renderable/Renderable.swift
  Example/SignUp/SignUpPresetner.swift
  Example/SignUp/SignUpRenderer.swift
  Example/SignUp/SignUpViewController.swift
Labels: ready for review

#157 Improve performance of estimated height queries.
  Bento.xcodeproj/project.pbxproj
  Bento/Adapters/AdapterStore.swift
  Bento/Adapters/TableViewAdapter.swift
  BentoTests/AdapterStoreItemTests.swift
  BentoTests/AdapterStoreTests.swift
Labels: ready for review

#88 Composable StyleSheet
  Bento.xcodeproj/project.pbxproj
  Bento/StyleSheets/StyleSheet.swift
  Bento/StyleSheets/StyleSheetProtocol.swift
  BentoTests/LegacyStyleSheetTests.swift
  BentoTests/StyleSheetTests.swift
Labels: ready for review

#159 Make `ComponentLifecycleAware` public.
  Bento/Renderable/ComponentLifecycleAware.swift
Labels: ready for review
