Repository Babylonpartners/Bento, pull requests merged in 2019-03, with the labels that each got.

#120 Fix bug for multiline button text
  BentoKit/BentoKit/Components/Button.swift
  BentoKit/BentoKitTests/SnapshotTests/Components/ButtonComponentSnapshotTests.swift
  Snapshots/ReferenceImages_64/BentoKitTests.ButtonComponentSnapshotTests/test_multiline_button_iPhone6@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.ButtonComponentSnapshotTests/test_multiline_button_iPhone6Plus@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.ButtonComponentSnapshotTests/test_multiline_button_iPhoneX@2x.png
Labels: bug, ready for review

#122 Remove hardcoded size for Toggle image
  BentoKit/BentoKit/Components/Toggle.swift
  BentoKit/BentoKitTests/SnapshotTests/Components/ToggleSnapshotTests.swift
  Snapshots/ReferenceImages_64/BentoKitTests.ToggleSnapshotTests/test_toggle_with_large_image_iPhone6@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.ToggleSnapshotTests/test_toggle_with_large_image_iPhone6Plus@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.ToggleSnapshotTests/test_toggle_with_large_image_iPhoneX@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.ToggleSnapshotTests/test_toggle_with_large_image_small_title_iPhone6@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.ToggleSnapshotTests/test_toggle_with_large_image_small_title_iPhone6Plus@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.ToggleSnapshotTests/test_toggle_with_large_image_small_title_iPhoneX@2x.png
Labels: enhancement, ready for review

#127 Remove `<>` operator
  Bento/Bento/Node.swift
  Bento/Views/Box.swift
  Example/Basic/ViewController.swift
  Example/BookAppoitment/BookAppointmentViewController.swift
  Example/CollectionViewExample/FoodListRenderer.swift
  Example/Movies/MoviesListViewController.swift
  Example/SignUp/SignUpRenderer.swift
Labels: enhancement, ready for review

#132 Use `.center` content mode of accessory view
  BentoKit/BentoKit/Views/Accessory.swift
Labels: bug

#128 Remove `If<T>` & `Some<T, U>`
  Bento/Bento/If.swift
  BentoTests/ConcatenationTests.swift
Labels: ready for review

#130 [BentoKit] Remove redundant associatedtype constraints
  BentoKit/BentoKit/Helpers/InputNodes.swift
  BentoKit/BentoKit/Helpers/NodeConstruction.swift
  BentoKit/BentoKit/Protocols/AutoRenderable.swift
Labels: ready for review

#129 [BentoKit] Fix broken playground
  BentoKit/BentoKit/Components.playground/Pages/Button.xcplaygroundpage/timeline.xctimeline
  BentoKit/BentoKit/Components.playground/Pages/MultilineTextInput.xcplaygroundpage/Contents.swift
  BentoKit/BentoKit/Components.playground/Pages/Search.xcplaygroundpage/Contents.swift
  BentoKit/BentoKit/Components.playground/Pages/TextInput.xcplaygroundpage/timeline.xctimeline
  BentoKit/BentoKit/Components.playground/Pages/TitledDescription.xcplaygroundpage/Contents.swift
  BentoKit/BentoKit/Components.playground/contents.xcplayground
Labels: ready for review

#133 Removes deprecated init
  BentoKit/BentoKit/Components/TitledDescription.swift
  BentoKit/BentoKitTests/SnapshotTests/Components/TitledDescriptionLegacySnapshotTests.swift
Labels: ready for review

#136 Make Description.StyleSheet inherit from InteractiveViewStyleSheet.
  BentoKit/BentoKit/Components/Description.swift
Labels: bug, ready for review
