Repository Babylonpartners/Bento, pull requests merged in 2019-06, with the labels that each got.

#175 Refactor StackView's stylesheet to avoid invalid configuration
  Bento.xcodeproj/project.pbxproj
  Bento/Components/DetailedDescription.swift
  Bento/StyleSheets/BaseStackViewStyleSheet.swift
  Bento/StyleSheets/StackViewStyleSheet.swift
  BentoTests/LegacyStyleSheetTests.swift
Labels: ready for review

#184 Add `extension String: Option`
  Bento/Components.playground/Pages/OptionPicker.xcplaygroundpage/Contents.swift
  Bento/Helpers/ListPickerAdapter.swift
  BentoTests/SnapshotTests/Components/OptionPickerSnapshotTests.swift
  Example/SignUp/SignUpViewController.swift
Labels: ready for review

#183 [CNSMR-1748] Attempt to fix crash in NSISEngine on deinit
  Bento/Views/BentoReusableView.swift
  Bento/Views/CollectionViewContainerCell.swift
  Bento/Views/CollectionViewContainerReusableView.swift
  Bento/Views/TableViewContainerCell.swift
  Bento/Views/TableViewHeaderFooterView.swift
Labels: ready for review

#186 Merge earlier approved patches re: components with dynamic heights.
  Bento/Bento/UITableViewExtensions.swift
  Bento/Views/Adapters/AdapterProtocol.swift
  Bento/Views/Adapters/AdapterStore.swift
  Bento/Views/Adapters/TableViewAdapter.swift
  Bento/Views/BentoTableView.swift
  BentoKit/BentoKit/Views/BoxSizeCachingTableView.swift
  BentoTests/AdapterStoreTests.swift
Labels: ready for review

#182 Add async-`CustomInput` support
  Bento/Decorators/CustomInputComponent.swift
  Bento/Views/FocusToolbar.swift
Labels: help wanted, ready for review

#187 Replacing `move` by `delete` and `insert` sections
  Bento/Diff/CollectionViewSectionDiff.swift
Labels: bug, ready for review
