Repository Babylonpartners/Bento, pull requests merged in 2019-05, with the labels that each got.

#161 Release 0.4.0 (develop)
  Bento.podspec
  BentoKit.podspec
Labels: ready for review

#93 Screen Lifecycle.
  BentoKit/BentoKit.xcodeproj/project.pbxproj
  BentoKit/BentoKit/Screen/BoxViewController.swift
  BentoKit/BentoKit/Screen/BoxViewModel.swift
  BentoKit/BentoKit/Screen/ScreenLifecycleEvent.swift
Labels: ready for review

#167 Remove `++` operator
  BentoKit/BentoKit.xcodeproj/project.pbxproj
  BentoKit/BentoKit/Helpers/NodeConstruction.swift
Labels: ready for review

#166 Adds AnyRenderableConvirtable
  Bento/Renderable/AnyRenderable.swift
  Bento/Renderable/Renderable.swift
Labels: enhancement, ready for review

#169 Change the access level of variables in BoxViewController
  BentoKit/BentoKit/Screen/BoxViewController.swift
Labels: ready for review

#171 Fix rendering issue with `PreSizingLayoutPassRequiring`
  Bento/Views/RequiringPreSizingLayoutPass.swift
Labels: bug, ready for review

#172 [MN-353] Make sure MultilineTextInputAware invalidates the size cache as appropriate.
  Bento/Adapters/AdapterProtocol.swift
  Bento/Adapters/AdapterStore.swift
  Bento/Views/BentoTableView.swift
  BentoTests/AdapterStoreTests.swift
Labels: bug, ready for review

#173 [MN-353] Make sure MultilineTextInputAware invalidates the size cache as appropriate in BentoKit.
  Bento/Adapters/AdapterProtocol.swift
  Bento/Bento/UITableViewExtensions.swift
  BentoKit/BentoKit/Views/BoxSizeCachingTableView.swift
Labels: bug, ready for review

#164 Collapse `ComponentLifecycleAware` into `Renderable`.
  Bento/Renderable/AnyRenderable.swift
  Bento/Renderable/ComponentLifecycleAware.swift
  Bento/Renderable/Renderable.swift
  Bento/Views/BentoReusableView.swift
  BentoTests/ComponentLifecycleAware.swift
Labels: ready for review

#162 [CNSMR-1590] New `willMount` and `willUnmount` hooks to support atomic component DSLs.
  Bento.xcodeproj/project.pbxproj
  Bento/Decorators/ComponentLifecycleAware.swift
  Bento/Decorators/CustomInputComponent.swift
  Bento/Decorators/Deletable.swift
  Bento/Decorators/Stylable.swift
  Bento/Diff/CollectionViewSectionDiff.swift
  Bento/Diff/TableViewSectionDiff.swift
  Bento/Renderable/AnyRenderable.swift
  Bento/Renderable/Renderable.swift
  Bento/Renderable/ViewStorage.swift
  Bento/Views/Adapters/AdapterProtocol.swift
  Bento/Views/Adapters/AdapterStore.swift
  Bento/Views/Adapters/BentoCollectionView.swift
  Bento/Views/Adapters/CollectionViewAdapter.swift
  Bento/Views/Adapters/FocusEligibilitySource.swift
  Bento/Views/Adapters/TableViewAdapter.swift
  Bento/Views/Adapters/TableViewAnimation.swift
  Bento/Views/Adapters/UIKit+BentoCollectionView.swift
  Bento/Views/BentoReusableView.swift
  Bento/Views/CollectionViewContainerCell.swift
  Bento/Views/CollectionViewContainerReusableView.swift
  Bento/Views/TableViewContainerCell.swift
  Bento/Views/TableViewHeaderFooterView.swift
  BentoTests/ComponentLifecycleAware.swift
  BentoTests/ComponentLifecycleTests.swift
Labels: enhancement, ready for review

#180 Add CustomDebugStringConvertible conformance to Box, Section and Node
  Bento/Bento/Node.swift
  Bento/Bento/Section.swift
  Bento/Views/Box.swift
Labels: ready for review

#177 Make `Section.init(id:items:supplements:)` public
  Bento/Bento/Section.swift
Labels: ready for review

#179 [CNSMR-1713] Custom Input should work with AnyRenderable.
  Bento.xcodeproj/project.pbxproj
  Bento/Decorators/CustomInputComponent.swift
  Bento/Views/BentoReusableView.swift
  Bento/Views/CollectionViewContainerCell.swift
  Bento/Views/CollectionViewContainerReusableView.swift
  Bento/Views/TableViewContainerCell.swift
  Bento/Views/TableViewHeaderFooterView.swift
  BentoTests/CustomInputTests.swift
Labels: bug, ready for review

#181 Fix components with customInputs not being rendered
  Bento.xcodeproj/project.pbxproj
  Bento/Decorators/CustomInputComponent.swift
  BentoTests/SnapshotTests/Components/CustomInputSnapshotTests.swift
  Snapshots/ReferenceImages_64/BentoTests.CustomInputSnapshotTests/test_component_with_customInput_visible_iPhone6@2x.png
  Snapshots/ReferenceImages_64/BentoTests.CustomInputSnapshotTests/test_component_with_customInput_visible_iPhone6Plus@2x.png
  Snapshots/ReferenceImages_64/BentoTests.CustomInputSnapshotTests/test_component_with_customInput_visible_iPhoneX@2x.png
Labels: ready for review
