Repository Babylonpartners/Bento, pull requests merged in 2019-01, with the labels that each got.

#87 Remove the Equatable requirement on components.
  Bento.xcodeproj/project.pbxproj
  Bento/Bento/Node.swift
  Bento/Bento/Section.swift
  Bento/Bento/UITableViewExtensions.swift
  Bento/Diff/Changeset+MutationIndexPairs.swift
  Bento/Diff/ChangesetExtensions.swift
  Bento/Diff/CollectionViewSectionDiff.swift
  Bento/Diff/ComponentContract.md
  Bento/Diff/TableViewSectionDiff.swift
  Bento/Helpers.swift
  Bento/Renderable/AnyRenderable.swift
  Bento/Renderable/Renderable.swift
  BentoTests/AnyRenderableTests.swift
  BentoTests/NodeTests.swift
  BentoTests/SectionTests.swift
Labels: ready for review

#92 Migrate to Swift 4.2
  Bento.xcodeproj/project.pbxproj
  Bento/Adapters/CollectionViewAdapter.swift
  Bento/Adapters/TableViewAdapter.swift
  Bento/Adapters/TableViewAnimation.swift
  Bento/Bento/Supplement.swift
  Bento/Renderable/AnyRenderable.swift
  Bento/Views/TableViewContainerCell.swift
  Example/BookAppointmentViewController.swift
  Example/PersonalDetailsViewController.swift
  Example/ViewController.swift
Labels: ready for review

#91 [CE-141] Invalidate accessory view size when changing it's type
  BentoKit/BentoKit/Views/Accessory.swift
Labels: bug

#90 Update top view insets on safe area changes
  BentoKit/BentoKit/Screen/BoxViewController.swift
Labels: bug

#86 Add behaviours to the components
  Bento.xcodeproj/project.pbxproj
  Bento/Adapters/TableViewAdapter.swift
  Bento/Renderable/AnyRenderable.swift
  Bento/Renderable/ComponentLifecycleAware.swift
  Bento/Renderable/Deletable.swift
  Bento/Renderable/Renderable.swift
  BentoKit/BentoKit/Components/TitledDescription.swift
  BentoTests/ComponentLifecycleAware.swift
  BentoTests/DeletableTests.swift
  Example/Cells/MovieComponentView.swift
  Example/CollectionViewExample/IntroComponent.swift
  Example/ViewController.swift
Labels: enhancement, ready for review

#96 Update Podspec Swift version to 4.2
  Bento.podspec
Labels: bug, ready for review

#72 Option to disable first responder ascension upon interaction.
  BentoKit/BentoKit.xcodeproj/project.pbxproj
  BentoKit/BentoKit/Components/Button.swift
  BentoKit/BentoKit/Components/Description.swift
  BentoKit/BentoKit/Components/Image.swift
  BentoKit/BentoKit/Components/InteractionBehavior.swift
  BentoKit/BentoKit/Components/TitledDescription.swift
  BentoKit/BentoKit/Helpers/HighlightingGesture.swift
  BentoKit/BentoKit/Views/Accessory.swift
Labels: ready for review
