Repository Babylonpartners/Bento, pull requests merged in 2019-02, with the labels that each got.

#103 Mention the component contract in the README.
  README.md
Labels: ready for review

#99 Allow customizing Button type
  BentoKit/BentoKit/Components/Button.swift
  BentoKit/BentoKitTests/SnapshotTests/Components/ButtonComponentSnapshotTests.swift
  Snapshots/ReferenceImages_64/BentoKitTests.ButtonComponentSnapshotTests/test_custom_hugs_content_iPhone6@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.ButtonComponentSnapshotTests/test_custom_hugs_content_iPhone6Plus@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.ButtonComponentSnapshotTests/test_custom_hugs_content_iPhoneX@2x.png
Labels: bug, enhancement, ready for review

#105 Adds image edge insets to the button stylesheets
  StyleSheets/StyleSheets/ButtonStyleSheet.swift
Labels: ready for review

#104 Update FlexibleDiff to 0.0.7.
  Bento.podspec
  Cartfile
  Cartfile.resolved
  StyleSheets.podspec
Labels: ready for review

#106 Fix a UICollectionView diff application issue.
  Bento.xcodeproj/project.pbxproj
  Bento/Adapters/CollectionViewAdapter.swift
  Bento/Adapters/TableViewAdapter.swift
  Bento/Diff/CollectionViewSectionDiff.swift
  Bento/Diff/TableViewSectionDiff.swift
  BentoTests/UIKitContainerDiffApplicationTests.swift
Labels: bug, ready for review

#107 Remove `FlexibleDiff` as a dependency of BentoKit.
  BentoKit.podspec
Labels: ready for review

#102 Update the component contract for recently introduced behaviours.
  Bento/Diff/ComponentContract.md
Labels: ready for review

#109 Adds support for leading and trailing horizontal alignment.
  BentoKit/BentoKit/Components/Button.swift
  BentoKit/BentoKitTests/SnapshotTests/Components/ButtonComponentSnapshotTests.swift
  Snapshots/ReferenceImages_64/BentoKitTests.ButtonComponentSnapshotTests/test_leading_alignment_iPhone6@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.ButtonComponentSnapshotTests/test_leading_alignment_iPhone6Plus@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.ButtonComponentSnapshotTests/test_leading_alignment_iPhoneX@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.ButtonComponentSnapshotTests/test_trailing_alignment_iPhone6@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.ButtonComponentSnapshotTests/test_trailing_alignment_iPhone6Plus@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.ButtonComponentSnapshotTests/test_trailing_alignment_iPhoneX@2x.png
Labels: enhancement, ready for review

#108 Make sure TitledDescription respects `textBlockWidthFraction` when calculating the height
  BentoKit/BentoKit/Components/TitledDescription.swift
  BentoKit/BentoKitTests/SnapshotTests/Components/TitledDescriptionSnapshotTests.swift
  Snapshots/ReferenceImages_64/BentoKitTests.TitledDescriptionSnapshotTests/test_long_detail_with_fraction_and_fixed_number_of_lines_iPhone6@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.TitledDescriptionSnapshotTests/test_long_detail_with_fraction_and_fixed_number_of_lines_iPhone6Plus@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.TitledDescriptionSnapshotTests/test_long_detail_with_fraction_and_fixed_number_of_lines_iPhoneX@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.TitledDescriptionSnapshotTests/test_long_detail_with_fraction_iPhone6@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.TitledDescriptionSnapshotTests/test_long_detail_with_fraction_iPhone6Plus@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.TitledDescriptionSnapshotTests/test_long_detail_with_fraction_iPhoneX@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.TitledDescriptionSnapshotTests/test_long_detail_with_fraction_with_fixed_number_of_lines_iPhone6@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.TitledDescriptionSnapshotTests/test_long_detail_with_fraction_with_fixed_number_of_lines_iPhone6Plus@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.TitledDescriptionSnapshotTests/test_long_detail_with_fraction_with_fixed_number_of_lines_iPhoneX@2x.png
Labels: bug

#110 Add TextFieldStylesheet to TextInput component
  BentoKit/BentoKit/Components/TextInput.swift
  StyleSheets/StyleSheets/TextStyleSheet.swift
  StyleSheets/StyleSheetsTests/StyleSheetTests.swift
Labels: enhancement, ready for review

#113 Added contentView to TextInput
  BentoKit/BentoKit/Components/TextInput.swift
  BentoKit/BentoKitTests/SnapshotTests/Components/TextInputSnapshotTests.swift
  Snapshots/ReferenceImages_64/BentoKitTests.TextInputSnapshotTests/testTextInput_with_contentStyle_iPhone6@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.TextInputSnapshotTests/testTextInput_with_contentStyle_iPhone6Plus@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.TextInputSnapshotTests/testTextInput_with_contentStyle_iPhoneX@2x.png
Labels: enhancement, ready for review

#114 Add as any renderable method to `Renderable`
  Bento/Renderable/Renderable.swift
Labels: enhancement, ready for review

#112 Update the UIKit Integration Tests.
  BentoTests/UIKitContainerDiffApplicationTests.swift
Labels: ready for review

#100 Simplify the Renderable contract.
  Bento.xcodeproj/project.pbxproj
  Bento/Adapters/CollectionViewAdapter.swift
  Bento/Adapters/TableViewAdapter.swift
  Bento/Bento/Node.swift
  Bento/Bento/Section.swift
  Bento/Renderable/AnyRenderable.swift
  Bento/Renderable/ComponentLifecycleAware.swift
  Bento/Renderable/Deletable.swift
  Bento/Renderable/NativeView.swift
  Bento/Renderable/Renderable.swift
  Bento/Views/BentoReusableView.swift
  BentoTests/AnyRenderableTests.swift
  BentoTests/RenderableTests.swift
Labels: bug, ready for review

#115 Added support for a content view to MultilineTextInput
  BentoKit/BentoKit/Components/MultilineTextInput.swift
  BentoKit/BentoKitTests/SnapshotTests/Components/MultilineTextInputSnapshotTests.swift
  Snapshots/ReferenceImages_64/BentoKitTests.MultilineTextInputSnapshotTests/testShowingPlaceholderWhenHavingNoText_iPhone6@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.MultilineTextInputSnapshotTests/testShowingPlaceholderWhenHavingNoText_iPhone6Plus@2x.png
  Snapshots/ReferenceImages_64/BentoKitTests.MultilineTextInputSnapshotTests/testShowingPlaceholderWhenHavingNoText_iPhoneX@2x.png
Labels: enhancement, ready for review

#117 Fix button component having multiple buttons
  BentoKit/BentoKit/Components/Button.swift
Labels: bug, ready for review
